<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Details des commandes</title>
    <link rel="stylesheet" href="css/main.css" />
    
</head>
<body>
     <section>
     <h1>Bons de commande</h1>

        <a href="index.php">Retourner à l'accueil</a>

         <article class="order-form-customer">
            <h2><?= $customer['customerName'] ?></h2>
            <p><?= $customer['contactFirstName'] ?> <?= $customer['contactLastName'] ?></p>
            <p></p>
            <p><?= $customer['addressLine1'] ?> <br><?= $customer['city'] ?></p>
         </article>
       
            
        <table class="standard-table">
            <caption>Bon de commande n° <?= $_GET['order'] ?> </caption>
            <thead>
                
                <tr>
                    <th>Nom du produit</th>
                    <th>Quantité</th>
                    <th>Prix unitaire</th>
                    <th>Prix total</th>
                </tr>
            </thead>
                
             <tbody>
                <?php foreach ($ship as $shipped): ?>
                <tr>
                    <th><?= $shipped['productName'] ?></th>
                    <th> <?= $shipped['priceEach'] ?> €</th>
                    <th><?= $shipped['quantityOrdered'] ?></th>
                    <th><?= $number_francais = number_format($shipped['Total'], 2, ',', ' ') ?> €</th>
                </tr>
                <?php endforeach ?>
            </tbody>
             <tfoot>
                <tr>
                    <th colspan="3">Montant Total HT</th>
                    <th><?= $ht = number_format($result['totalFinal'], 2) ?> €</th>
                </tr>
                <tr>
                    <th colspan="3">TVA (20 %)</th>
                    <th><?= $tva = number_format($result['totalFinal'] * 0.20, 2) ?> €</th>
                </tr>
                <tr>
                    <th colspan="3">Montant Total TTC</th>
                    
                    <th><?= $ttc = number_format($result['totalFinal'] * 1.20, 2) ?> €</th>
                </tr>
            </tfoot>
        </table>
        </section>
</body>
</html>